version: "1.0"
services:
  csv-client:
    build:
      context: cli/
      dockerfile: Dockerfile
    environment:
      CSV_API_URL: http://csv-api:4000
    ports:
      - "3000:3000"
    networks:
      - local
  csv-api:
    build:
      context: api/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - local
networks:
  local:
    driver: bridge
